server:
  port: 8081
  tomcat:
    max-connections: 200            # ?? ?? ?? ?

  # ?? ??? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB      # ??? ? ? ?? ? ?? ??
      max-request-size : 200MB  # ??? ??? ? ??
  web:
    resources:
      static-locations : file:///C:/uploadFiles/   # ?? ??? ??
#      static-locations : file:///Users/??/uploadFiles/
      cache-period: 3600                           # ? ????? ?? ??(?, 1??)


filepath: C:/uploadFiles
#filepath: /Users/??/uploadFiles